### ISSUE TITLE
Cross Compilation issue

### ISSUE THREAD

**Issue by I3atMan27** [Seagate/openSeaChest#12]
Hi,

should be nice to have makefile with :
CC ?= gcc
instead of :
CC = gcc

**Comment by xahmad** [comment]
Changed the Makefile, including in all the submodules. 

BTW, we have been using the following command line for the cross compilation in our build script and it has worked so far, i.e. without the ?= changes. 

make CC=arm-linux-gnueabi-gcc AR=arm-linux-gnueabi-ar STRIP=arm-linux-gnueabi-strip

But ?= is better. Thanks for the suggestion.
