### ISSUE TITLE
Text files (.txt) a bit out of date compared with ToolBin

### ISSUE THREAD

**Issue by edrozenberg** [Seagate/openSeaChest#35]
Comparing 

https://github.com/Seagate/openSeaChest/tree/develop/docs

with

https://github.com/Seagate/ToolBin/tree/master/openSeaChest/docs

I see that the ToolBin docs are newer versions.

Not a big deal.

**Comment by rudock1** [comment]
Hi @edrozenberg 
Thanks for the reminder.  Just did a refresh so I think they are getting closer in synch now.

**Comment by edrozenberg** [comment]
Sounds great thanks!
