### ISSUE TITLE
release tarballs aren't buildable

### ISSUE THREAD

**Issue by asomers** [Seagate/openSeaChest#6]
The release tarballs don't include the git submodules, which makes them unbuildable.  Tested on OpenSeaChest 18.04 with the release tarball posted on GitHub.

**Comment by xahmad** [comment]
We are working on a 18.10 release which will be finished before the end of this month and it should have all the FreeBSD fixes.

**Comment by thesamesam** [comment]
ping

**Comment by vonericsen** [comment]
I added a new action that will create a `Source_With_Submodules.tar.xz` and `Source_With_Submodules.zip` when we push release tags.

It seems that the default for a release uses git archive which does not traverse submodules. I read up on this issue (multiple git repos on Github have similar issues filed) and it seems `git-archive-all` is the best solution to use, so this new Github action will use that to publish these at the releases going forward.

**Comment by thesamesam** [comment]
Thank you!

**Comment by faithanalog** [comment]
I see the new tarball in the alpha release https://github.com/Seagate/openSeaChest/releases/tag/v23.02-alpha.1, and it looks to build just fine for me. I think it is a little weird that the folder extracts to `Source_With_Submodules.` and I'd maybe prefer it extract to `openSeaChest-23.02-alpha.1` to match the release version. But that's pretty minor. Thanks for adding this!

**Comment by vonericsen** [comment]
@faithanalog I will investigate changing that to the version you mentioned. I think that would make a lot more sense.

**Comment by vonericsen** [comment]
This has been fixed in https://github.com/Seagate/openSeaChest/releases/tag/v23.03
I even got the subfolder to have a nice name like @faithanalog mentioned previously! 😄 

If you have any trouble, please feel free to reopen this issue and I will look at this again.
