### ISSUE TITLE
Remove "sas" tag

### ISSUE THREAD

**Issue by allanbowe** [Seagate/openSeaChest#63]
The vast majority of repositories under the "SAS" tag are in relation to SAS Software, not Serial Attached SCSI.

Would you consider removing or re-naming the SAS tag in this repo?  Given you are in the top 10 repositories for "sas" !

https://github.com/topics/sas

**Comment by vonericsen** [comment]
Hi @allanbowe,
Thanks for bringing this to our attention.
I have removed the SAS tag since I can understand why that would be confusing 😄 
I updated our other repo "ToolBin" for this as well.

**Comment by allanbowe** [comment]
Thanks!
