### ISSUE TITLE
Arguments/options missing after installation

### ISSUE THREAD

**Issue by DevinCampbell** [Seagate/openSeaChest#92]
I installed openSeaChest on my Ubuntu 22.04.1 LTS host using the following commands:

```
sudo git clone --recurse-submodules --branch develop https://github.com/Seagate/openSeaChest.git openSeaChest-develop
cd openSeaChest-develop/Make/gcc && make release
mkdir -pv /opt/openSeaChest/bin && cp openseachest_exes/* /opt/openSeaChest/bin
```

However, when I run `openSeaChest_Security --help` I am only seeing some of the arguments/options listed instead of everything in https://support.seagate.com/seachest/SeaChest_Combo_UserGuides.html#file12.

Specifically, I am trying to completely wipe and format a Seagate ST6000NM0054 drive that seems to be encrypted and I believe to do that I need to run something like `openSeaChest_Security -d /dev/disk/by-id/<diskname> --psid <psid> --revertSP` but when I do I get an output saying it doesn't recognize --psid or --revertSP. Using the --help option doesn't list these options/arguments in it. 

Why does my installation of openSeaChest not include all of the options/arguments as the GitHub repo? I don't typically build my own software from repos so I'm guessing I probably did something wrong there.

**Comment by vonericsen** [comment]
Hi @DevinCampbell,

Currently the revertSP and PSID options are not supported in openSeaChest. SeaChest vs openSeaChest are very similar and this happens to be one of the few differences at this time.

We do have a Linux version of SeaChest you can [download from our Toolbin repo](https://github.com/Seagate/ToolBin) that will run those commands for you. Here is a [direct link](https://github.com/Seagate/ToolBin/raw/master/SeaChest/Security/v3.0.5/Linux/SeaChest_Security_x86_64-alpine-linux-musl_static) to SeaChest_Security for Linux that should download for you without having to naviagte Github's UI to get it.

This build should also be part of the SeaChest package on Seagate.com

While the executable is named with "alpine-linux-musl_static", it is not unique to running on Alpine Linux. It should run without error on your Ubuntu 20.04 as well.

Let me know if you have any other trouble.
